### ISSUE TITLE
Incorrect parsing of top-level function application under some circumstances

### ISSUE THREAD

**Issue by apatil** [JuliaLang/JuliaParser.jl#15]
Hi Jake,

I have some code to parse:
```julia
s = "0\na(b)"
ts = Lexer.TokenStream(s)
```

The second expression, `a(b)`, parses correctly as a substring:

```julia
julia> Parser.parse(s[2:end])
:(a(b))
```

but the second expression doesn't get parsed correctly when I try to do the whole thing as a token stream:

```julia
julia> Parser.parse(ts)
0

julia> Parser.parse(ts)
:a

julia> Parser.parse(ts)
:b
```

Thanks!

**Comment by jakebolewski** [comment]
@apatil thanks for the report, definitely looks like a bug.
