### ISSUE TITLE
Update for recent parser changes.

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/JuliaParser.jl#19]
There has been some changes to the julia parser and this packages seems to be not in sync anymore. Apart from the doc string changes, there are three of my PR's that relaxes some of the restrictions for parsing. https://github.com/JuliaLang/julia/pull/11345, https://github.com/JuliaLang/julia/pull/11338, https://github.com/JuliaLang/julia/pull/11333.

In particular, the new syntax allowed by https://github.com/JuliaLang/julia/pull/11333 seems to be causing https://github.com/IainNZ/Coverage.jl/issues/77

@kshyatt

**Comment by jrevels** [comment]
I can take a crack at fixing the breakage caused by JuliaLang/julia#11333 today. If I'm not misunderstanding, I just need to make [this function](https://github.com/jakebolewski/JuliaParser.jl/blob/master/src/parser.jl#L1072) consistent with the logic applied [here](https://github.com/yuyichao/julia/commit/33ab0f623bfd44ea45784db263c1d4d7dff94eec), yes?

**Comment by yuyichao** [comment]
Should be. Also make sure it passes these tests https://github.com/yuyichao/julia/commit/b2c2d42fe928b49532c4480af2902b35cf8b7b10

**Comment by Keno** [comment]
I updated this package such that is passes all it's current tests. If you write new ones for these parser changes, I can fix them as well.

**Comment by tkelman** [comment]
> FactCheck finished with 51 non-successful tests.

**Comment by Keno** [comment]
You're always so negative! I was discounting https://github.com/JuliaLang/julia/issues/14658

**Comment by tkelman** [comment]
Forgot about that one, sorry. We have new nightlies now, if that makes a difference. Still best to do something about the tests on release julia before we consider tagging this again though.

**Comment by Keno** [comment]
Done.

**Comment by yuyichao** [comment]
=) :+1:
