### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/JuliaParser.jl#23]
Could a new version be tagged? The [atom-julia-client](https://github.com/JunoLab/atom-julia-client/tree/master/manual) installation instructions right now tell people to checkout ``JuliaParser``, if a new release was tagged that step could probably be eliminated, right? Given that the Atom stuff was mentioned recently on the mailing list, it would be nice to have an easy setup experience.

@one-more-minute

**Comment by MikaelSlevinsky** [comment]
+1.

I use Juno in LightTable all the time. Upgrading to v0.4 Julia and to have a functioning IDE required me to clone the master branches of:

Julia-LT
Juno-LT

into the Application Support/plugins and checkout the master branches of:

Jewel.jl
JuliaParser.jl
LNR.jl
Lazy.jl

**Comment by davidanthoff** [comment]
@jakebolewski any reason to not just tag a new release?

**Comment by jiahao** [comment]
He's been busy with other work at the moment. Do be patient.

**Comment by jakebolewski** [comment]
I haven't completely caught up to 0.4 but tagging a new release with partial progress shouldn't hurt.

**Comment by davidanthoff** [comment]
Yep, agree, thanks! I think this would just make things easier for users of the Atom client.

**Comment by ssfrr** [comment]
Ping on tagging a new release. This and Hiccup.jl are the last two packages still showing deprecation warnings with their latest tagged versions. Checking out master seems to work with no warnings.

**Comment by hayd** [comment]
closed by https://github.com/JuliaLang/METADATA.jl/pull/4234 ?

**Comment by davidanthoff** [comment]
I think so!
