### ISSUE TITLE
Move to JuliaLang

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/JuliaParser.jl#30]
The native Julia parser is needed by other projects like the IDE, so it would make sense to house it under JuliaLang so that others can help keep up with changes to the base language.

**Comment by Ismael-VC** [comment]
@jiahao @jakebolewski could you please give me some status about this?

**Comment by EricForgy** [comment]
:+1:

**Comment by jakebolewski** [comment]
I believe that this is in process, @StefanKarpinski can close when this is complete.

**Comment by EricForgy** [comment]
Cool

https://github.com/JuliaLang/JuliaParser.jl
