### ISSUE TITLE
Add a Gitter channel badge.

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/JuliaParser.jl#41]
I'd like to propose the creation of a Gitter chat room and the inclusion of a badge to this repository README, this would allow us to communicate more widely, meet each other, share ideas and get feedback in a more real time fashion and iterate faster among those ideas, ask questions specific to JuliaParser, etc. and that are not necessarily as technical or formal nor expected to be as ever lasting as issues and PRs must  be and even goof around a while, why not?

Some examples, that in my experience have been very useful to boost Julia and also individual projects in the Julian community:

* https://gitter.im/JuliaLang/julia
* https://gitter.im/kshyatt/julia-coverage
* https://gitter.im/JuliaLangEs/julialang-es
* https://gitter.im/JunoLab/Juno
* https://gitter.im/BioJulia/Bio.jl
* https://gitter.im/JuliaGraphs/LightGraphs.jl
* https://gitter.im/dcjones/Gadfly.jl
* https://gitter.im/IntelLabs/ParallelAccelerator.jl

And many many more! :smile: 

I'm very glad to see lots of improvements on this repo, which I'm trying to use to implement a Julia multi-language parser, and hopefully some time I may even be able to propose a way to integrate it into Julia proper. As I learn and experiment I have lots of doubts about the code, which I would like to help document, but since precisely I don't know and understand all of the code, I would like to have a place where I can ask you guys questions that will help me reach 100% documentation of all the current code related to this project. Which would help us scratch the third bullet in the TODO list about *modularization* for library use.

I'm sure most of my doubts are not worthy of opening an issue, please tell me what you think, I even think it would be nice to have this on each and every one of the Julia repos. I know there are forums, and other venues, but I have to say I like chatting even more and so do others! :wink: 

* https://gitter.im/orgs/JuliaLang/rooms

In order to do this you need to log into gitter with a github account, select *create room*, select *from repository*, and select this repo, then select integrations and select Github, that triggers a PR from the gitter-badger bot.

**Comment by jakebolewski** [comment]
I don't think packages like this get enough traffic to really warrant a dedicated chat channel. I think well thought out Issues are best for discussion or even better actual code :)

**Comment by Keno** [comment]
+1 I agree with @jakebolewski. One of my biggest frustrations is that relevant discussion in chat do not get captured in issues.

**Comment by Ismael-VC** [comment]
> I don't think packages like this get enough traffic to really warrant a dedicated chat channel. 

Couldn't we have at least tried? The channel can be removed and it can't hurt anyone.

> I think well thought out Issues are best for discussion or even better actual code :)

As I said I don't understand all your code so helping with actual code is almost imposible for me right now, I guess I'll have to use issues for everything then, sorry in advance then, in case you may think some of my issues are stupid and obvious.

> One of my biggest frustrations is that relevant discussion in chat do not get captured in issues.

Fair enough, I think that is a cultural issue, and I'm always trying to teach people to report issues. But I guess this chat room wouldn't be of much use if you the devs don't use it anyway.

**Comment by Keno** [comment]
If you feel like the question is not worth an issue, how about emailing julia-users with cc to me. I will try to answer and there is at least a permanent record of the discussion.

**Comment by Ismael-VC** [comment]
@Keno I will do that thanks, I've already started, see: https://github.com/JuliaLang/JuliaParser.jl/issues/44 and https://github.com/JuliaLang/JuliaParser.jl/pull/45 Please tell me if you think I should keep asking those kind of questions here or there, I tried to make those a well thought issue and PR, which will be ongoing.
