### ISSUE TITLE
The directions for enabling the fancy parsing mode don't seem to work.

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/JuliaParser.jl#42]
This is probably my fault, but I tried the following:

```
JuliaParser/bin [master] » julia -q -L repl.jl
julia> for i = 1:
ERROR: syntax: missing last argument in "1:" range expression
 in eval(::Module, ::Any) at ./boot.jl:237
```

This seems to be using the error messages from the original flisp parser.

**Comment by jakebolewski** [comment]
cc @Keno

**Comment by Keno** [comment]
I fixed the immediate bug, but there's another bug in showing the error for your expression. I'll take a look at that later.

**Comment by jakebolewski** [comment]
Thanks!

**Comment by Keno** [comment]
7a3f721a8231846fcffafcad1364370178780765
