### ISSUE TITLE
Error JuliaParser with Julia 0.4.5 win7 x64

### ISSUE THREAD

**Issue by cnzxcxt1** [JuliaLang/JuliaParser.jl#50]
Hello,
I got this error message when I try to install "JuliaParser" this package.
It has troubled me for a whole day. 
could you help me to have a look at it?
thanks
INFO: Cloning cache of JuliaParser from https://github.com/JuliaLang/JuliaParser.jl.git
ERROR: failed process: Process(`git clone -q --mirror https://github.com/JuliaLang/JuliaParser.jl.git 'C:\Users\CHEN Xia
ngtuo\.julia\v0.4\.cache\JuliaParser'`, ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23

**Comment by jakebolewski** [comment]
@cnzxcxt1 this is because the latest master version of `JuliaParser` requires julia version v0.5+.
