### ISSUE TITLE
syntax: invalid operator ".!"

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/JuliaParser.jl#60]
Version 0.5.0-rc0+0 (2016-07-26 20:22 UTC)
x86_64-w64-mingw32

julia> using JuliaParser
ERROR: LoadError: LoadError: syntax: invalid operator ".!"
 in include_from_node1(::String) at .\loading.jl:426 (repeats 2 times)
 in eval(::Module, ::Any) at .\boot.jl:234
 in require(::Symbol) at .\loading.jl:357
while loading C:\Users\necka\.julia\v0.5\JuliaParser\src\lexer.jl, in expression starting on line 46
while loading C:\Users\necka\.julia\v0.5\JuliaParser\src\JuliaParser.jl, in expression starting on line 9

**Comment by KristofferC** [comment]
Probably need a newer commit than rc0+0. Works on latest master for me.

**Comment by rapus95** [comment]
that means that rc0+0 wasn't built after the feature freeze?

**Comment by KristofferC** [comment]
Maybe it was a bug fix :p

**Comment by rapus95** [comment]
Clarification seems not to be worth a single word... :/

**Comment by KristofferC** [comment]
works for me on rc0+0 as well

```jl
julia> using JuliaParser

julia> versioninfo()
Julia Version 0.5.0-rc0+0
Commit 0030eec (2016-07-26 20:22 UTC)
```

**Comment by jakebolewski** [comment]
@rapus95 I am getting this package ready to work on v0.5, but getting it to work on all pre-release versions is not an explicit goal.  If you still see this error as we work to v0.5, please say something.

**Comment by rapus95** [comment]
@jakebolewski ok thanks, it seems to be a strange bug since it works at some places and doesn't at some other places :/
for me it still errors. my "fix" is replacing `:(.!)` by `Symbol(".!")`

**Comment by jakebolewski** [comment]
@rapus95 the only place where that symbol is defined is https://github.com/JuliaLang/JuliaParser.jl/blob/51ec76163936e0b4ecf39e46e63fa5ac6c2842a2/src/lexer.jl#L47

so I don't know why you are getting that error.

It seems worrying that behavior here is different on Windows / Unix  for the same release candidate if that is indeed what you are seeing.  The only way I could see that happening is that the rc for the windows builds is not built off the same commit as the tagged rc.

**Comment by KristofferC** [comment]
That is what the current code has: https://github.com/JuliaLang/JuliaParser.jl/blob/51ec76163936e0b4ecf39e46e63fa5ac6c2842a2/src/lexer.jl#L47

**Comment by rapus95** [comment]
forget all i said until now... checkout to master obviously solved it -.-

But there still remains one question. What is .! for? the parser somehow doesn't seem to be able to parse it since the expression has to be written as a String. So how would i be able to use the operator without manually constructing the expression?

**Comment by tkelman** [comment]
Always best to give `Pkg.status()` with all bug reports (or `versioninfo(true)`). The tagged version of this package doesn't work with rc0, but master here is apparently in better shape.
