### ISSUE TITLE
REPL: jl_uv_writecb() broken pipe EPIPE

### ISSUE THREAD

**Issue by Ismael-VC** [JuliaLang/JuliaParser.jl#63]
This happens on Windows 10 64 bits, with versions `0.5.0-rc0+76` and `0.6.0-dev.62` when trying to run `bin/repl.jl`:

``` julia
C:\Users\Ismael>C:\Julia-0.6\bin\julia.exe C:\Users\Ismael\.julia\v0.6\JuliaParser\bin\repl.jl
jl_uv_writecb() ERROR: broken pipe EPIPE
⋮
jl_uv_writecb() ERROR: broken pipe EPIPE

C:\Users\Ismael>
```

I had this version:

``` julia
julia> Pkg.status("JuliaParser")
 - JuliaParser                   0.7.4
```

After that I tried to checkout the package, on v5.0 I get the same error as above, but now even more **surprising** is that after checking out on 0.6 now Windows doesn't even let me execute the command, even if I use Administrator privileges, I tried freeing the package again to v0.7.4 but it seems Windows has locked it up somehow and won't let me run it anymore, I would appreciate if someone could try to reproduce this bug.

Here are some screenshots:

![damn](https://cloud.githubusercontent.com/assets/4594825/17577191/7798fa2c-5f40-11e6-82b4-723a53a0124c.PNG)

Error says: _This application cannot be executed on this computer_

![damn2](https://cloud.githubusercontent.com/assets/4594825/17577192/7798f482-5f40-11e6-9464-c02fd3e3669d.PNG)

Error says _access denied_

I think Microsoft just banned me from doing that WTF!? :angry: It's the first time I ever face this pop up on Windows with **any** program.

**Comment by Ismael-VC** [comment]
I'll try to wipe out the 0.6 install and try if windows bans the executable again.

**Comment by jakebolewski** [comment]
@Ismael-VC  are still seeing this?

**Comment by KristofferC** [comment]
Cross reffing this: https://github.com/KristofferC/PimpMyREPL.jl/issues/14. There we found that `redirect_stderr` is causing it in that particular case.

**Comment by KristofferC** [comment]
You are probably doing something the same to overwrite some of the REPL methods with the JuliaParser functions?

**Comment by Ismael-VC** [comment]
@jakebolewski yes, I can confirm this is still happening, I have just updated my Windows 10 and tested again, I don't get blocked by Windows anymore,  but the IO error remains the same.

I have asked at SO, @Keno has answered me there but I don't understand what does he mean, and anyway my `@suppress` macros are based directly from the code in the JuliaParser repl, made by Keno himself.

* https://github.com/Ismael-VC/Suppressor.jl
* http://stackoverflow.com/questions/39170298/how-to-create-a-macro-that-suppresses-errors-and-warnings

So it is not clear to me how to solve this issue.
